### ISSUE TITLE
Login View의 Login Button hotfix 진행하려고 합니다!

### ISSUE THREAD

**Issue by eomiso** [wafflestudio19-5/team4-iOS#20]
혹시 그동안 LoginViewController와 SignUpViewController 수정하실 일이 있으신가요?
제가 #19 에서 언급한 SignUP 시에 에러가 아마 비밀번호 입력 란이 맡에 margin UIView에 잘려서 그런것 같은데, 수정하는 김에 제가 같이 손보려구요.
괜찮을까요?

혹시나 나중에 충돌날까봐 미리 여쭤봅니다!

**Comment by MinnieMinwoo** [comment]
아니요 따로 수정할일은 아직 없을거 같아요!

**Comment by eomiso** [comment]
아 지금 다시 뜯어보니까 제가 생각했던 문제가 아니네요 ㅠㅜ 
민우님께서 해결해보시겠어요?
아니면 제가 만든 LogInView에서 View 가져와서 그대로 덮어씌우는 것도 방법일 것 같구요 ㅠㅜ
일단 #20 에서 LOgin버튼 UI 오류 해결한것 먼저 풀리퀘 날려두겠습니다.
