### ISSUE TITLE
Custom Table View Cell의 크기를 동적으로 할당하는 방법?

### ISSUE THREAD

**Issue by MinnieMinwoo** [wafflestudio19-5/team4-iOS#52]
일단 UI는 다 완성을 했는데, 이부분에서 막히고 있네요..

원래 뷰컨 상에서 다음과 같이 정의하고

```Swift
func addPostTableView() { //Table View를 설정하는 메서드
        postTableView.dataSource = self
        postTableView.delegate = self
        postTableView.estimatedRowHeight = 50
        postTableView.rowHeight = UITableView.automaticDimension
        postTableView.register(PostTableViewCell.self, forCellReuseIdentifier: PostTableViewCell.identifier)
        view.addSubview(postTableView)
        //.....    }
```

delegate에서는 
```Swift
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return postTableView.rowHeight
    }
```
automaticDimension으로 설정된 값을 불러오도록 해서 tableview의 높이 설정을 동적으로 할 수 있는 것으로 알 수 있습니다. 그런데 height값이 기본값 (estimatedRowHeight도 아닌 tableview에 아무런 설정을 하지 않았을 때의 초기값)으로만 출력이 되는거 같네요 ㅜㅜ 그래서 문제를 찾아오던 중 코드를 확인해보니

```Swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: PostTableViewCell.identifier) as? PostTableViewCell else { return PostTableViewCell() }
        return cell
    }
```
이 부분에 cell의 height을 출력하도록 해보니 cell의 높이가 기본값인 44로 고정이 되는 현상을  확인했습니다.
<img width="367" alt="스크린샷 2022-01-13 오후 9 12 29" src="https://user-images.githubusercontent.com/80435894/149328285-108d0837-5a9e-42cf-b72c-8023ebe538e5.png">

혹시 이 상황에서 정상적으로 cell의 height를 설정할 수 있는 방법을 아실까요..?

**Comment by MinnieMinwoo** [comment]
<img width="318" alt="스크린샷 2022-01-13 오후 9 12 05" src="https://user-images.githubusercontent.com/80435894/149328171-46d6b0ec-cd28-443b-8248-0d17c4e1a9c0.png">

**Comment by eomiso** [comment]
1. 일단 estimated height는 실제로 height에 영향을 미치는 녀석이 아니라, 단순히 UI loading 속도를 올려주는데 도움이 되는 녀석인 것으로 알고 있습니다.
2. 그런데 아래 사진을 보면 높이가 44 보다는 무조건 클거 같은데 혹시 사진이 있는 Postview cell도 같은 높이 인지 확인해 보시겠어요?
<img width="428" alt="image" src="https://user-images.githubusercontent.com/17143087/149529132-4c19b807-e7f8-4309-968d-6ea4631a5bc5.png">
 - 3번째 코드에서 cell이 아직 constraint가적용 되기 전 상태를 가지고 있는거면 44로 고정된 프린트 결과물이 나올 수도 있을 것 같은데 실제 UI 상에서는 이미 Dynamic 하게 적용되고 있는 것처럼 보여서요

**Comment by MinnieMinwoo** [comment]
cell은 코드
```Swift
func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return postTableView.rowHeight
    }
```
여기서 임의로 값을 줘서(160) 정상적으로 보이는 거에요..! 아마 생성시에 cell height가 지정이 안되는게 문제인거 같긴 하네요..
